package com.tfg.bpp.adapter.client;

import v1.service.CreateBppMetricsByBppInstancesProto.CreateBppMetricsByBppInstancesRequest;
import v1.service.CreateBppMetricsByBppInstancesProto.CreateBppMetricsByBppInstancesResponse;
import v1.service.CreateBppMetricsByBppRandomInstancesProto.CreateBppMetricsByBppRandomInstancesRequest;
import v1.service.CreateBppMetricsByBppRandomInstancesProto.CreateBppMetricsByBppRandomInstancesResponse;
import v1.service.CreateBppSolutionsBySolvableInstancesProto.CreateBppSolutionsByBppSolvableInstancesRequest;
import v1.service.CreateBppSolutionsBySolvableInstancesProto.CreateBppSolutionsByBppSolvableInstancesResponse;

public interface BinPackingProblemCoreGrpcClient {

  CreateBppSolutionsByBppSolvableInstancesResponse createBppSolutionsByBppSolvableInstances(
      CreateBppSolutionsByBppSolvableInstancesRequest
          createBppSolutionsByBppSolvableInstancesRequest);

  CreateBppMetricsByBppRandomInstancesResponse createBppMetricsByBppRandomInstances(
      CreateBppMetricsByBppRandomInstancesRequest createBppMetricsByBppRandomInstancesRequest);

  CreateBppMetricsByBppInstancesResponse createBppMetricsByBppInstances(
      CreateBppMetricsByBppInstancesRequest createBppMetricsByBppInstancesRequest);
}
